export const seedQuestions = [
  {
    "sortOrder": 1,
    "difficulty": "MEDIUM",
    "textUz": "Bojxona statistikasi ma’lumotlarini guruhlash usuli asosida tahlil qilishda quyidagilardan qaysi biri asosiy tahlil yo‘nalishlaridan biri sifatida keltirilmagan?",
    "textRu": "",
    "optionAUz": "TIF subyektlari bo‘yicha",
    "optionARu": "",
    "optionBUz": "Davlatlar va hududlar bo‘yicha",
    "optionBRu": "",
    "optionCUz": "Tovar pozitsiyalari bo‘yicha",
    "optionCRu": "",
    "optionDUz": "Korxonaning ichki mehnat intizomi bo‘yicha",
    "optionDRu": "",
    "correctOption": "D",
    "isActive": true
  },
  {
    "sortOrder": 2,
    "difficulty": "MEDIUM",
    "textUz": "Chizma (grafik) usulda bojxona statistikasi obyektlarining o‘zgarish dinamikasini ifodalash uchun eng ko‘p qo‘llanadigan diagramma turi qaysi?",
    "textRu": "",
    "optionAUz": "Aylana diagramma",
    "optionARu": "",
    "optionBUz": "Chiziqli diagramma",
    "optionBRu": "",
    "optionCUz": "Nuqtali diagramma",
    "optionCRu": "",
    "optionDUz": "Gistogramma",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 3,
    "difficulty": "MEDIUM",
    "textUz": "Chiziqli grafik yordamida bojxona statistikasi dinamikasi ifodalanayotganda o‘qlar qanday joylashtiriladi?",
    "textRu": "",
    "optionAUz": "Abssissa o‘qiga qiymat, ordinata o‘qiga vaqt",
    "optionARu": "",
    "optionBUz": "Har ikki o‘qqa faqat foiz ko‘rsatkichlari",
    "optionBRu": "",
    "optionCUz": "Abssissa o‘qiga vaqt oralig‘i, ordinata o‘qiga qiymat yoki miqdor",
    "optionCRu": "",
    "optionDUz": "Abssissa o‘qiga davlatlar, ordinata o‘qiga boj stavkasi",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 4,
    "difficulty": "MEDIUM",
    "textUz": "Tashqi savdo balansi jadvalida tashqi savdo aylanmasi qanday aniqlanadi?",
    "textRu": "",
    "optionAUz": "Eksport − import",
    "optionARu": "",
    "optionBUz": "Eksport + import",
    "optionBRu": "",
    "optionCUz": "Eksport / import",
    "optionCRu": "",
    "optionDUz": "Import − eksport",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 5,
    "difficulty": "MEDIUM",
    "textUz": "Agar eksport qiymati import qiymatidan yuqori bo‘lsa, tashqi savdo balansi qanday baholanadi?",
    "textRu": "",
    "optionAUz": "Passiv balans",
    "optionARu": "",
    "optionBUz": "Neytral balans",
    "optionBRu": "",
    "optionCUz": "Aktiv balans",
    "optionCRu": "",
    "optionDUz": "Kredit balans",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 6,
    "difficulty": "MEDIUM",
    "textUz": "Eksport va import qiymatlari o‘zaro teng bo‘lsa, bu holat qanday ataladi?",
    "textRu": "",
    "optionAUz": "Passiv saldo",
    "optionARu": "",
    "optionBUz": "Aktiv saldo",
    "optionBRu": "",
    "optionCUz": "Netto-balans",
    "optionCRu": "",
    "optionDUz": "Tovar balansi",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 7,
    "difficulty": "HARD",
    "textUz": "Indeks usulida alohida (individual) indeks odatda qaysi harf bilan belgilanadi?",
    "textRu": "",
    "optionAUz": "I",
    "optionARu": "",
    "optionBUz": "i",
    "optionBRu": "",
    "optionCUz": "R",
    "optionCRu": "",
    "optionDUz": "q",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 8,
    "difficulty": "HARD",
    "textUz": "Alohida indeksning umumiy ko‘rinishi qaysi formula bilan ifodalanadi?",
    "textRu": "",
    "optionAUz": "i=X0/X1",
    "optionARu": "",
    "optionBUz": "i=X1−X0",
    "optionBRu": "",
    "optionCUz": "i=X1/X0",
    "optionCRu": "",
    "optionDUz": "i=X1+X0",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 9,
    "difficulty": "HARD",
    "textUz": "Tovar fizik hajmining alohida indeksini ko‘rsating.",
    "textRu": "",
    "optionAUz": "iq=q1/q0",
    "optionARu": "",
    "optionBUz": "iq=p1/p0",
    "optionBRu": "",
    "optionCUz": "iq=q0/q1",
    "optionCRu": "",
    "optionDUz": "iq=p0/p1",
    "optionDRu": "",
    "correctOption": "A",
    "isActive": true
  },
  {
    "sortOrder": 10,
    "difficulty": "HARD",
    "textUz": "Tovar bir birlik narxining alohida indeksini ko‘rsating.",
    "textRu": "",
    "optionAUz": "ip=q1/q0",
    "optionARu": "",
    "optionBUz": "ip=p1/p0",
    "optionBRu": "",
    "optionCUz": "ip=p0/p1",
    "optionCRu": "",
    "optionDUz": "ip=q0/q1",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 11,
    "difficulty": "HARD",
    "textUz": "Agar alohida indeks 1 dan katta bo‘lsa, bu nimani bildiradi?",
    "textRu": "",
    "optionAUz": "Ko‘rsatkich o‘zgarmaganini",
    "optionARu": "",
    "optionBUz": "Ko‘rsatkich kamayganini",
    "optionBRu": "",
    "optionCUz": "Ko‘rsatkich oshganini",
    "optionCRu": "",
    "optionDUz": "Hisoblashda xato borligini",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 12,
    "difficulty": "HARD",
    "textUz": "Tovar qiymati indeksining umumiy formulasi qaysi?",
    "textRu": "",
    "optionAUz": "Ipq=Σp1q1/Σp0q0",
    "optionARu": "",
    "optionBUz": "Ipq=Σp1q0/Σp0q1",
    "optionBRu": "",
    "optionCUz": "Ipq=Σp0q1/Σp1q0",
    "optionCRu": "",
    "optionDUz": "Ipq=Σp1/Σp0",
    "optionDRu": "",
    "correctOption": "A",
    "isActive": true
  },
  {
    "sortOrder": 13,
    "difficulty": "HARD",
    "textUz": "Joriy davrdagi fizik hajm o‘zgarmas deb olinib, narxning tovar qiymatiga ta’sirini aniqlovchi formula qaysi?",
    "textRu": "",
    "optionAUz": "Iq=Σp0q1/Σp0q0",
    "optionARu": "",
    "optionBUz": "Ip=Σp1q1/Σp0q1",
    "optionBRu": "",
    "optionCUz": "Ip=Σp1q0/Σp0q0",
    "optionCRu": "",
    "optionDUz": "Ipq=Σp1q1/Σp0q0",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 14,
    "difficulty": "HARD",
    "textUz": "Asos davrdagi narx o‘zgarmas deb olinib, fizik hajmning tovar qiymatiga ta’sirini ko‘rsatuvchi formula qaysi?",
    "textRu": "",
    "optionAUz": "Iq=Σp0q1/Σp0q0",
    "optionARu": "",
    "optionBUz": "Iq=Σp1q1/Σp1q0",
    "optionBRu": "",
    "optionCUz": "Iq=Σq1/Σq0",
    "optionCRu": "",
    "optionDUz": "Iq=Σp1q0/Σp0q1",
    "optionDRu": "",
    "correctOption": "A",
    "isActive": true
  },
  {
    "sortOrder": 15,
    "difficulty": "HARD",
    "textUz": "Quyidagi tengliklardan qaysi biri tovar qiymati indeksining narx va fizik hajm indekslari bilan bog‘liqligini to‘g‘ri ifodalaydi?",
    "textRu": "",
    "optionAUz": "Ipq=Ip+Iq",
    "optionARu": "",
    "optionBUz": "Ipq=Ip−Iq",
    "optionBRu": "",
    "optionCUz": "Ipq=Ip×Iq",
    "optionCRu": "",
    "optionDUz": "Ipq=Ip/Iq",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 16,
    "difficulty": "HARD",
    "textUz": "Laspeyres narx indeksi qaysi formula bilan ifodalanadi?",
    "textRu": "",
    "optionAUz": "Σp1q1/Σp0q1",
    "optionARu": "",
    "optionBUz": "Σp1q0/Σp0q0",
    "optionBRu": "",
    "optionCUz": "Σp0q1/Σp0q0",
    "optionCRu": "",
    "optionDUz": "Σp1q1/Σp0q0",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 17,
    "difficulty": "HARD",
    "textUz": "Sabab (faktor) usulining matematik ifodasi qaysi javobda to‘g‘ri berilgan?",
    "textRu": "",
    "optionAUz": "Y=x1+x2+...+xn",
    "optionARu": "",
    "optionBUz": "Y=X1/X0",
    "optionBRu": "",
    "optionCUz": "Y=f(x1,x2,...,xn)",
    "optionCRu": "",
    "optionDUz": "Y=p×q",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 18,
    "difficulty": "MEDIUM",
    "textUz": "Matnda keltirilishicha, davlat eksporti miqdoriga ta’sir ko‘rsatuvchi asosiy omillar qaysilar?",
    "textRu": "",
    "optionAUz": "Faqat boj stavkasi va QQS",
    "optionARu": "",
    "optionBUz": "Umummilliy mehnat unumdorligi va milliy daromad",
    "optionBRu": "",
    "optionCUz": "Faqat valyuta kursi va bank foizi",
    "optionCRu": "",
    "optionDUz": "Faqat transport xarajati va sug‘urta summasi",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 19,
    "difficulty": "MEDIUM",
    "textUz": "Matnda import hajmiga ta’sir ko‘rsatuvchi asosiy omil sifatida nima ko‘rsatilgan?",
    "textRu": "",
    "optionAUz": "Faqat bojxona postlari soni",
    "optionARu": "",
    "optionBUz": "Tashqi siyosiy reyting",
    "optionBRu": "",
    "optionCUz": "Xalq xo‘jaligi va aholining import tovarlarga bo‘lgan ehtiyoji",
    "optionCRu": "",
    "optionDUz": "Faqat eksportyor korxonalarning foydasi",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 20,
    "difficulty": "HARD",
    "textUz": "Tashqi savdo bojxona statistikasi ma’lumotlarini asosiy ko‘rsatkichlar bo‘yicha tahlil qilishning umumiy sxemasida, tahlil qilinuvchi kattaliklar sifatida qaysi javob to‘liqroq keltirilgan?",
    "textRu": "",
    "optionAUz": "Faqat netto vazn va boj stavkasi",
    "optionARu": "",
    "optionBUz": "Qo‘shimcha o‘lchov birligidagi miqdor, netto vazn, faktura, bojxona va statistik qiymat",
    "optionBRu": "",
    "optionCUz": "Faqat faktura qiymati va eksport boji",
    "optionCRu": "",
    "optionDUz": "Faqat statistik qiymat va transport turi",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 21,
    "difficulty": "HARD",
    "textUz": "Mamlakatlar tashqi savdo bojxona statistikasi ma’lumotlarini tahliliy solishtirishdan asosiy maqsad nima?",
    "textRu": "",
    "optionAUz": "Faqat eksport bojlarini kamaytirish",
    "optionARu": "",
    "optionBUz": "Statistik ma’lumotlarni qiyosiy baholash orqali tafovutlar, xatolar va yashirin holatlarni aniqlash",
    "optionBRu": "",
    "optionCUz": "Faqat import hajmini oshirish",
    "optionCRu": "",
    "optionDUz": "Faqat bojxona postlari sonini ko‘paytirish",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 22,
    "difficulty": "MEDIUM",
    "textUz": "Tayanch so‘z va iboralarda keltirilgan quyidagi tushunchalardan qaysi biri mamlakatlararo bojxona statistikasi ma’lumotlarini solishtirish bilan bevosita bog‘liq emas?",
    "textRu": "",
    "optionAUz": "Qamrov darajasi",
    "optionARu": "",
    "optionBUz": "Operatsion ko‘rsatkich",
    "optionBRu": "",
    "optionCUz": "Texnik tafovutlar",
    "optionCRu": "",
    "optionDUz": "Kontragent mamlakat",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 23,
    "difficulty": "HARD",
    "textUz": "Mamlakatlar o‘rtasida tashqi savdo bojxona statistikasi ma’lumotlarida tafovutlar kelib chiqishining asosiy sabablari qaysilar?",
    "textRu": "",
    "optionAUz": "Faqat valyuta kursi o‘zgarishi",
    "optionARu": "",
    "optionBUz": "Faqat transport xarajatlari",
    "optionBRu": "",
    "optionCUz": "Uslubiy tafovutlar, texnik tafovutlar va noto‘g‘ri ma’lumot taqdim etish",
    "optionCRu": "",
    "optionDUz": "Faqat boj stavkalari farqi",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 24,
    "difficulty": "MEDIUM",
    "textUz": "Quyidagilardan qaysi biri uslubiy tafovut hisoblanadi?",
    "textRu": "",
    "optionAUz": "Tovar import mamlakatiga hali yetib bormaganligi",
    "optionARu": "",
    "optionBUz": "Tovar tranzitda yo‘qolganligi",
    "optionBRu": "",
    "optionCUz": "Tovar statistik qiymatini importda CIF, eksportda esa DAF shartida aniqlash",
    "optionCRu": "",
    "optionDUz": "Tovar taqqoslanayotgan davrdan keyin yetib kelganligi",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 25,
    "difficulty": "MEDIUM",
    "textUz": "Quyidagilardan qaysi biri texnik tafovut hisoblanadi?",
    "textRu": "",
    "optionAUz": "TIF TN qoidalarini turlicha talqin qilish",
    "optionARu": "",
    "optionBUz": "Tovar ishlab chiqarilgan mamlakatni noto‘g‘ri ko‘rsatish",
    "optionBRu": "",
    "optionCUz": "Tovar eksport mamlakatidan jo‘natilib, import mamlakatiga taqqoslanayotgan davrda hali yetib kelmagan bo‘lishi",
    "optionCRu": "",
    "optionDUz": "Jismoniy shaxslar olib o‘tgan tovarlarni turlicha hisobga olish",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 26,
    "difficulty": "MEDIUM",
    "textUz": "Ma’lumotlarni solishtirishda eksport qiluvchi mamlakat ma’lumotlari import qiluvchi mamlakat ma’lumotlaridan katta bo‘lsa, quyidagilardan qaysi holat bunga sabab bo‘lishi mumkin?",
    "textRu": "",
    "optionAUz": "Tovar import mamlakatiga uchinchi mamlakat orqali etkazib berilgan",
    "optionARu": "",
    "optionBUz": "Tovar import mamlakatiga hali yetib bormagan",
    "optionBRu": "",
    "optionCUz": "Import mamlakatida avval olib kirilgan tovar bojxona rasmiylashtiruvidan o‘tkazilgan",
    "optionCRu": "",
    "optionDUz": "Tovar eksport mamlakatidan noqonuniy yo‘l bilan olib chiqilgan",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 27,
    "difficulty": "MEDIUM",
    "textUz": "Eksport qiluvchi mamlakat ma’lumotlari import qiluvchi mamlakat ma’lumotlaridan kichik bo‘lsa, qaysi holat ehtimoliy sabab bo‘la oladi?",
    "textRu": "",
    "optionAUz": "Tovar import mamlakatining bojxona omborida turibdi",
    "optionARu": "",
    "optionBUz": "Tovar import mamlakatiga noqonuniy olib kirilgan",
    "optionBRu": "",
    "optionCUz": "Tovar import mamlakatiga uchinchi mamlakat orqali etkazib berilmoqda",
    "optionCRu": "",
    "optionDUz": "Tovar hali yo‘lda",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 28,
    "difficulty": "MEDIUM",
    "textUz": "Quyidagilardan qaysi holat noto‘g‘ri ma’lumot taqdim qilish misoli sifatida keltirilgan?",
    "textRu": "",
    "optionAUz": "Tovar tranzit mamlakatda shikastlangan",
    "optionARu": "",
    "optionBUz": "Importer bojxona to‘lovlaridan qochish maqsadida qalbaki invoys taqdim qilishi",
    "optionBRu": "",
    "optionCUz": "Hisobot davri bir xil kelmasligi",
    "optionCRu": "",
    "optionDUz": "Tovar bojxona omborida saqlanayotgan bo‘lishi",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 29,
    "difficulty": "MEDIUM",
    "textUz": "Eksportyorlar tomonidan qaytarib olinadigan QQS miqdorini oshirish uchun qaysi usul qo‘llanishi mumkinligi matnda ko‘rsatilgan?",
    "textRu": "",
    "optionAUz": "Tovar miqdori va qiymatini kamaytirib ko‘rsatish",
    "optionARu": "",
    "optionBUz": "Tovar nomini yashirish",
    "optionBRu": "",
    "optionCUz": "Tovar miqdori va qiymatini oshirib ko‘rsatish",
    "optionCRu": "",
    "optionDUz": "Tovarni umuman deklaratsiya qilmaslik",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 30,
    "difficulty": "HARD",
    "textUz": "Mamlakatlar o‘rtasida ma’lumotlarni solishtirishda uslubiy tafovutlarni hisobga olish uchun alohida tahlil qilinadigan yo‘nalishlardan qaysi biri to‘g‘ri?",
    "textRu": "",
    "optionAUz": "Faqat bojxona xodimlari soni",
    "optionARu": "",
    "optionBUz": "Ma’lumotlarning qamrov darajasi, savdo tizimi, hisobga olish vaqti, klassifikatsiya va kontragent mamlakat",
    "optionBRu": "",
    "optionCUz": "Faqat davlat byudjeti ko‘rsatkichlari",
    "optionCRu": "",
    "optionDUz": "Faqat ichki bozor narxlari",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 31,
    "difficulty": "MEDIUM",
    "textUz": "Matnga ko‘ra, mamlakatlar o‘rtasida tashqi savdo bojxona statistikasi ma’lumotlarini o‘zaro solishtirish jarayoni nimaga yakun yasaydi?",
    "textRu": "",
    "optionAUz": "Sud qarori chiqarish bilan",
    "optionARu": "",
    "optionBUz": "Bojxona posti xulosasi bilan",
    "optionBRu": "",
    "optionCUz": "Qo‘shimcha ma’lumot taqdim qilish belgilangan bayonnomaning imzolanishi bilan",
    "optionCRu": "",
    "optionDUz": "Faqat og‘zaki kelishuv bilan",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 32,
    "difficulty": "VERY_HARD",
    "textUz": "O‘zbekiston Respublikasi Davlat bojxona qo‘mitasi va Turkmaniston Davlat bojxonasi o‘rtasidagi “Tashqi savdo bojxona statistikasi sohasida uslubiy va axborot hamkorligi to‘g‘risida”gi Bayonnoma qachon imzolangan?",
    "textRu": "",
    "optionAUz": "2010 yil 9 iyun",
    "optionARu": "",
    "optionBUz": "2011 yil 1 yanvar",
    "optionBRu": "",
    "optionCUz": "2001 yil 27 fevral",
    "optionCRu": "",
    "optionDUz": "2005 yil 15 mart",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 33,
    "difficulty": "MEDIUM",
    "textUz": "Turkmaniston–O‘zbekiston misolida o‘zaro solishtirish natijasida qaysi tovar bo‘yicha tafovut aniqlangan?",
    "textRu": "",
    "optionAUz": "Shakar",
    "optionARu": "",
    "optionBUz": "Tozalangan paxta yog‘i",
    "optionBRu": "",
    "optionCUz": "Bug‘doy uni",
    "optionCRu": "",
    "optionDUz": "Elektr energiyasi",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 34,
    "difficulty": "MEDIUM",
    "textUz": "Turkmaniston tomoni ma’lumotida tozalangan paxta yog‘ining birlik narxi qancha ko‘rsatilgan?",
    "textRu": "",
    "optionAUz": "1,15 dollar/kg",
    "optionARu": "",
    "optionBUz": "1,67 dollar/kg",
    "optionBRu": "",
    "optionCUz": "2,15 dollar/kg",
    "optionCRu": "",
    "optionDUz": "0,97 dollar/kg",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 35,
    "difficulty": "MEDIUM",
    "textUz": "O‘zbekiston tomoni import ma’lumotida shu tovarning birlik qiymati qancha ko‘rsatilgan?",
    "textRu": "",
    "optionAUz": "1,67 dollar/kg",
    "optionARu": "",
    "optionBUz": "1,50 dollar/kg",
    "optionBRu": "",
    "optionCUz": "1,15 dollar/kg",
    "optionCRu": "",
    "optionDUz": "0,75 dollar/kg",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 36,
    "difficulty": "MEDIUM",
    "textUz": "Turkmaniston va O‘zbekiston bojxona organlari ma’lumotlarini solishtirish natijasida qo‘shimcha qancha bojxona to‘lovlari hisoblangan?",
    "textRu": "",
    "optionAUz": "37,3 mln so‘m",
    "optionARu": "",
    "optionBUz": "173,3 mln so‘m",
    "optionBRu": "",
    "optionCUz": "273,3 mln so‘m",
    "optionCRu": "",
    "optionDUz": "373,3 mln so‘m",
    "optionDRu": "",
    "correctOption": "D",
    "isActive": true
  },
  {
    "sortOrder": 37,
    "difficulty": "VERY_HARD",
    "textUz": "Ekspertlar uchrashuvidan kamida qancha muddat oldin tomonlar tovarlar ro‘yxati haqida bir-birlarini xabardor qiladilar?",
    "textRu": "",
    "optionAUz": "1 hafta",
    "optionARu": "",
    "optionBUz": "2 hafta",
    "optionBRu": "",
    "optionCUz": "3 hafta",
    "optionCRu": "",
    "optionDUz": "1 oy",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 38,
    "difficulty": "MEDIUM",
    "textUz": "Ekspertlar guruhi ishining ikkinchi bosqichida asosan nima amalga oshiriladi?",
    "textRu": "",
    "optionAUz": "Faqat yangi boj stavkalari belgilanadi",
    "optionARu": "",
    "optionBUz": "Tafovutlar sabablarini aniqlash va kelishib olish maqsadida ekspertlar uchrashuvi o‘tkaziladi",
    "optionBRu": "",
    "optionCUz": "Faqat import hajmi e’lon qilinadi",
    "optionCRu": "",
    "optionDUz": "Faqat statistik hudud aniqlanadi",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 39,
    "difficulty": "MEDIUM",
    "textUz": "Zarur hollarda, agar ma’lumotlarni oshkor etish milliy qonunchilikka zid kelmasa, solishtirish qaysi darajada o‘tkazilishi mumkin?",
    "textRu": "",
    "optionAUz": "Faqat yillik umumiy ko‘rsatkichlar darajasida",
    "optionARu": "",
    "optionBUz": "Faqat choraklik ma’lumotlar darajasida",
    "optionBRu": "",
    "optionCUz": "Aniq bir etkazib berilgan tovar partiyasi darajasida",
    "optionCRu": "",
    "optionDUz": "Faqat davlatlar guruhi darajasida",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 40,
    "difficulty": "MEDIUM",
    "textUz": "Yakuniy hujjatda quyidagilardan qaysi biri albatta aks etishi lozim?",
    "textRu": "",
    "optionAUz": "Faqat ekspertlar guruhi tarkibi",
    "optionARu": "",
    "optionBUz": "Faqat solishtirish natijasi",
    "optionBRu": "",
    "optionCUz": "Solishtirish maqsadi, davr oralig‘i, ekspertlar guruhi tarkibi, natija, tafovutlar sababi, xulosa va takliflar",
    "optionCRu": "",
    "optionDUz": "Faqat qo‘shimcha boj summasi",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 41,
    "difficulty": "VERY_HARD",
    "textUz": "Bojxona yuk deklaratsiyasi kim tomonidan to‘ldiriladi va kim tomonidan rasmiylashtiriladi?",
    "textRu": "",
    "optionAUz": "Bojxona inspektori to‘ldiradi, deklarant rasmiylashtiradi",
    "optionARu": "",
    "optionBUz": "Deklaratsiyalovchi shaxs to‘ldiradi, bojxona inspektori rasmiylashtiradi",
    "optionBRu": "",
    "optionCUz": "Faqat tashuvchi to‘ldiradi",
    "optionCRu": "",
    "optionDUz": "Faqat bojxona brokeri rasmiylashtiradi",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 42,
    "difficulty": "MEDIUM",
    "textUz": "Ma’lumotlarning haqqoniyligi deganda nima tushuniladi?",
    "textRu": "",
    "optionAUz": "Faqat BYDdagi qiymatning bozor narxiga mosligi",
    "optionARu": "",
    "optionBUz": "Faqat tovar kodi to‘g‘ri ko‘rsatilishi",
    "optionBRu": "",
    "optionCUz": "BYDdagi ma’lumotlarning to‘liqligi, to‘g‘ri to‘ldirilganligi va rasmiylashtirilganligi",
    "optionCRu": "",
    "optionDUz": "Faqat bojxona to‘lovlarining hisoblanganligi",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 43,
    "difficulty": "VERY_HARD",
    "textUz": "BYDni to‘ldirishda ko‘p uchraydigan xatolar nechta asosiy toifaga bo‘linadi?",
    "textRu": "",
    "optionAUz": "2 ta",
    "optionARu": "",
    "optionBUz": "3 ta",
    "optionBRu": "",
    "optionCUz": "4 ta",
    "optionCRu": "",
    "optionDUz": "5 ta",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 44,
    "difficulty": "MEDIUM",
    "textUz": "Quyidagilardan qaysi biri PPTda keltirilgan xato turlaridan biri emas?",
    "textRu": "",
    "optionAUz": "Texnik xatoliklar",
    "optionARu": "",
    "optionBUz": "Ob’yektiv xatoliklar",
    "optionBRu": "",
    "optionCUz": "Sub’yektiv xatoliklar",
    "optionCRu": "",
    "optionDUz": "Kriminogen xatoliklar",
    "optionDRu": "",
    "correctOption": "D",
    "isActive": true
  },
  {
    "sortOrder": 45,
    "difficulty": "VERY_HARD",
    "textUz": "BYDning 46-grafasida qiymat 1000 AQSH dollarida ifodalanmay, bu holat inspektorning e’tiborsizligi oqibatida yuzaga kelsa, bu qanday xatolik hisoblanadi?",
    "textRu": "",
    "optionAUz": "Ob’yektiv xatolik",
    "optionARu": "",
    "optionBUz": "Statistik xatolik",
    "optionBRu": "",
    "optionCUz": "Texnik xatolik",
    "optionCRu": "",
    "optionDUz": "Sub’yektiv xatolik",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 46,
    "difficulty": "VERY_HARD",
    "textUz": "BYDning 46-grafasidagi xato yetkazib berish shartlari, faktura qiymati yoki bojxona qiymati noto‘g‘ri aniqlangani natijasida yuzaga kelsa, bu qanday xatolik bo‘ladi?",
    "textRu": "",
    "optionAUz": "Texnik xatolik",
    "optionARu": "",
    "optionBUz": "Sub’yektiv xatolik",
    "optionBRu": "",
    "optionCUz": "Tashkiliy xatolik",
    "optionCRu": "",
    "optionDUz": "Rasmiy xatolik",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 47,
    "difficulty": "MEDIUM",
    "textUz": "Quyidagi grafalardan qaysi biri tovarning statistik qiymatini aks ettiradi?",
    "textRu": "",
    "optionAUz": "42-grafa",
    "optionARu": "",
    "optionBUz": "45-grafa",
    "optionBRu": "",
    "optionCUz": "46-grafa",
    "optionCRu": "",
    "optionDUz": "47-grafa",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 48,
    "difficulty": "MEDIUM",
    "textUz": "Quyidagi grafalardan qaysi biri bojxona to‘lovlarini noto‘g‘ri hisoblash bilan bog‘liq?",
    "textRu": "",
    "optionAUz": "33-grafa",
    "optionARu": "",
    "optionBUz": "47-grafa",
    "optionBRu": "",
    "optionCUz": "29-grafa",
    "optionCRu": "",
    "optionDUz": "25-grafa",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 49,
    "difficulty": "VERY_HARD",
    "textUz": "BYDning 24-grafasida “61” kodi ko‘rsatilishi qaysi holatda PPTga ko‘ra xato deb topilgan?",
    "textRu": "",
    "optionAUz": "Eksportning erkin muomalaga chiqarish rejimida",
    "optionARu": "",
    "optionBUz": "Import IM-40 rejimida",
    "optionBRu": "",
    "optionCUz": "Bojxona ombori rejimida",
    "optionCRu": "",
    "optionDUz": "Tranzit rejimida",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 50,
    "difficulty": "VERY_HARD",
    "textUz": "BYDning 24-grafasida “61” kodini IM-40 rejimida qo‘llash oqibatida qanday natija yuzaga kelgani ko‘rsatilgan?",
    "textRu": "",
    "optionAUz": "Tovar ikki marta deklaratsiya qilingan",
    "optionARu": "",
    "optionBUz": "19,0 ming AQSH dollarilik tovar statistika hisobidan chiqib ketgan",
    "optionBRu": "",
    "optionCUz": "Bojxona to‘lovlari ortiqcha undirilgan",
    "optionCRu": "",
    "optionDUz": "Tovar kelib chiqish mamlakati noto‘g‘ri ko‘rsatilgan",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 51,
    "difficulty": "MEDIUM",
    "textUz": "Qo‘shma korxona o‘zi ishlab chiqargan mahsulotni eksport qilayotganda 37-grafada “1000027” ko‘rsatilsa, 43-grafada nima ko‘rsatiladi?",
    "textRu": "",
    "optionAUz": "0",
    "optionARu": "",
    "optionBUz": "1",
    "optionBRu": "",
    "optionCUz": "27",
    "optionCRu": "",
    "optionDUz": "1000",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 52,
    "difficulty": "VERY_HARD",
    "textUz": "BYDning 8-grafasidagi STIR (INN) ma’lumotlari noto‘g‘ri ko‘rsatilganini aniqlashda qaysi manbadan foydalaniladi?",
    "textRu": "",
    "optionAUz": "Faqat bank ma’lumotlaridan",
    "optionARu": "",
    "optionBUz": "Faqat bojxona posti jurnalidan",
    "optionBRu": "",
    "optionCUz": "Davlat statistika va soliq qo‘mitalarining yagona davlat registri ma’lumotlaridan",
    "optionCRu": "",
    "optionDUz": "Faqat eksportyorning xatidan",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 53,
    "difficulty": "VERY_HARD",
    "textUz": "BYDning 23-grafasida qaysi kurs ko‘rsatilishi kerak?",
    "textRu": "",
    "optionAUz": "Shartnoma tuzilgan kundagi kurs",
    "optionARu": "",
    "optionBUz": "Tovar jo‘natilgan kundagi kurs",
    "optionBRu": "",
    "optionCUz": "BYD bojxona rasmiylashtiruviga qabul qilingan kundagi Markaziy bank kursi",
    "optionCRu": "",
    "optionDUz": "Hisobot oyining oxirgi kunidagi kurs",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 54,
    "difficulty": "VERY_HARD",
    "textUz": "BYDning 29-grafasida “26003” kodi va post nomi ko‘rsatilgan bo‘lsa, bu holat qanday baholanadi?",
    "textRu": "",
    "optionAUz": "Har doim to‘g‘ri",
    "optionARu": "",
    "optionBUz": "Noto‘g‘ri, chunki TIF bojxona posti kodi va nomini ko‘rsatish xato",
    "optionBRu": "",
    "optionCUz": "Faqat eksportda xato",
    "optionCRu": "",
    "optionDUz": "Faqat tranzitda xato",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 55,
    "difficulty": "VERY_HARD",
    "textUz": "Qaysi TIF bojxona postlarini 29-grafada ko‘rsatish amaliyotda xato hisoblanmaydi?",
    "textRu": "",
    "optionAUz": "26003 va 06011",
    "optionARu": "",
    "optionBUz": "00102 “Avia yuklar” va 12012 “Navoiy industrial”",
    "optionBRu": "",
    "optionCUz": "27020 va 26010",
    "optionCRu": "",
    "optionDUz": "14010 va 35002",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 56,
    "difficulty": "VERY_HARD",
    "textUz": "BYDning 31-grafasi chap past qismidagi STIR kod raqamlari bo‘yicha qaysi hukm to‘g‘ri?",
    "textRu": "",
    "optionAUz": "Ularni to‘ldirish ixtiyoriy",
    "optionARu": "",
    "optionBUz": "Faqat eksportda to‘ldiriladi",
    "optionBRu": "",
    "optionCUz": "To‘ldirilishi shart",
    "optionCRu": "",
    "optionDUz": "Faqat jismoniy shaxs uchun to‘ldiriladi",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 57,
    "difficulty": "VERY_HARD",
    "textUz": "BYDning 24-grafasida bitim xususiyati kodi “84” ko‘rsatilgan bo‘lsa, 37-grafa 3-bo‘linmasida nima ko‘rsatiladi?",
    "textRu": "",
    "optionAUz": "027",
    "optionARu": "",
    "optionBUz": "084",
    "optionBRu": "",
    "optionCUz": "004",
    "optionCRu": "",
    "optionDUz": "040",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 58,
    "difficulty": "VERY_HARD",
    "textUz": "BYDning 1-grafasida tovar harakati yo‘nalishi “IM” bo‘la turib, 37-grafa 3-bo‘linmasida “027” kodi ko‘rsatilishi qanday baholanadi?",
    "textRu": "",
    "optionAUz": "To‘g‘ri, chunki bu import kodi",
    "optionARu": "",
    "optionBUz": "Xato, chunki tovarni olib o‘tish xususiyati kodi yo‘nalish yoki rejimga mos emas",
    "optionBRu": "",
    "optionCUz": "Faqat vaqtincha olib kirishda to‘g‘ri",
    "optionCRu": "",
    "optionDUz": "Faqat statistikada qo‘llanadi",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 59,
    "difficulty": "VERY_HARD",
    "textUz": "Toshkent shahar bojxona boshqarmasiga qarashli TIF bojxona postlarida aniqlangan xatolar ichida eng katta ulush qaysi grafaga to‘g‘ri kelgan?",
    "textRu": "",
    "optionAUz": "46-grafa",
    "optionARu": "",
    "optionBUz": "31-grafa",
    "optionBRu": "",
    "optionCUz": "20-grafa",
    "optionCRu": "",
    "optionDUz": "8-grafa",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 60,
    "difficulty": "VERY_HARD",
    "textUz": "Toshkent shahar bojxona boshqarmasi ma’lumotiga ko‘ra, 20-grafa bo‘yicha aniqlangan xatolar ulushi qancha bo‘lgan?",
    "textRu": "",
    "optionAUz": "14,05%",
    "optionARu": "",
    "optionBUz": "15,27%",
    "optionBRu": "",
    "optionCUz": "9,01%",
    "optionCRu": "",
    "optionDUz": "8,75%",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 61,
    "difficulty": "VERY_HARD",
    "textUz": "Mazkur Nizom nimani belgilaydi?",
    "textRu": "",
    "optionAUz": "Faqat bojxona to‘lovlarini hisoblash tartibini",
    "optionARu": "",
    "optionBUz": "BYDni o‘zgartirish, qo‘shimcha kiritish, qayta rasmiylashtirish, qaytarib olish va bekor qilish tartibini",
    "optionBRu": "",
    "optionCUz": "Faqat eksport statistikasi yuritish tartibini",
    "optionCRu": "",
    "optionDUz": "Faqat bojxona ko‘rigini o‘tkazish tartibini",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 62,
    "difficulty": "VERY_HARD",
    "textUz": "Mazkur qaror qachondan kuchga kiradi?",
    "textRu": "",
    "optionAUz": "Rasmiy e’lon qilingan kundan boshlab",
    "optionARu": "",
    "optionBUz": "Imzolangan kundan 10 kun o‘tib",
    "optionBRu": "",
    "optionCUz": "Rasmiy e’lon qilingan kundan e’tiboran uch oydan keyin",
    "optionCRu": "",
    "optionDUz": "Adliya vazirligida ro‘yxatdan o‘tgan kundan boshlab",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 63,
    "difficulty": "VERY_HARD",
    "textUz": "BYDdagi xato deganda nima tushuniladi?",
    "textRu": "",
    "optionAUz": "Faqat tovar kodi noto‘g‘ri ko‘rsatilishi",
    "optionARu": "",
    "optionBUz": "Faqat yetishmayotgan hujjatlar",
    "optionBRu": "",
    "optionCUz": "Taqdim etilgan hujjatlardagi yoki bojxona organidagi axborot bilan BYD/BQD ma’lumotlari orasidagi tafovut yoxud grafalardagi noto‘g‘ri ma’lumot",
    "optionCRu": "",
    "optionDUz": "Faqat deklarantning imzosi yo‘qligi",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 64,
    "difficulty": "VERY_HARD",
    "textUz": "BYDdagi kamchilik deganda nima tushuniladi?",
    "textRu": "",
    "optionAUz": "Bojxona organi bilan deklarant o‘rtasidagi nizo",
    "optionARu": "",
    "optionBUz": "Zarur ma’lumotlar yetishmasligi yoki BYD bilan birga taqdim etilishi lozim bo‘lgan hujjatlarning to‘liq bo‘lmasligi",
    "optionBRu": "",
    "optionCUz": "Faqat qiymat noto‘g‘ri ko‘rsatilishi",
    "optionCRu": "",
    "optionDUz": "Faqat bojxona to‘lovlari kech to‘lanishi",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 65,
    "difficulty": "VERY_HARD",
    "textUz": "Rasmiylashtirilgan BYD qaysi belgi bilan ajratiladi?",
    "textRu": "",
    "optionAUz": "7-grafada faqat sana bo‘lishi bilan",
    "optionARu": "",
    "optionBUz": "“D” grafasiga bojxona organining tegishli belgilari qo‘yilgan bo‘lishi bilan",
    "optionBRu": "",
    "optionCUz": "1-grafa to‘ldirilgani bilan",
    "optionCRu": "",
    "optionDUz": "Faqat ERI bilan tasdiqlangani bilan",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 66,
    "difficulty": "VERY_HARD",
    "textUz": "Ro‘yxatga olinib, rasmiylashtirilmagan BYD qaysi holatni anglatadi?",
    "textRu": "",
    "optionAUz": "7-grafada raqam va sana bor, lekin “D” grafasiga tegishli belgilar qo‘yilmagan",
    "optionARu": "",
    "optionBUz": "Hech bir grafasi to‘ldirilmagan",
    "optionBRu": "",
    "optionCUz": "Faqat qog‘oz shaklda bo‘lgan BYD",
    "optionCRu": "",
    "optionDUz": "Bojxona organi tomonidan rad etilgan BYD",
    "optionDRu": "",
    "correctOption": "A",
    "isActive": true
  },
  {
    "sortOrder": 67,
    "difficulty": "VERY_HARD",
    "textUz": "Elektron shakldagi BYD qaysi javobda to‘g‘ri tariflangan?",
    "textRu": "",
    "optionAUz": "Faqat skaner qilingan hujjat",
    "optionARu": "",
    "optionBUz": "Deklaratsiyalovchi shaxs ERIsi bilan tasdiqlangan va TEDAAT orqali taqdim etilgan elektron hujjat",
    "optionBRu": "",
    "optionCUz": "Oddiy Word hujjati",
    "optionCRu": "",
    "optionDUz": "Faqat bojxona organi to‘ldiradigan shakl",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 68,
    "difficulty": "MEDIUM",
    "textUz": "BQDning to‘g‘ri tavsifi qaysi?",
    "textRu": "",
    "optionAUz": "BYDdan alohida, mustaqil statistik hisobot",
    "optionARu": "",
    "optionBUz": "BYDning ajralmas qismi bo‘lib, tovarning bojxona qiymati haqidagi ma’lumotlarni o‘z ichiga oladi",
    "optionBRu": "",
    "optionCUz": "Faqat eksportda tuziladigan hujjat",
    "optionCRu": "",
    "optionDUz": "Faqat bankka topshiriladigan hujjat",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 69,
    "difficulty": "VERY_HARD",
    "textUz": "Bojxona rasmiylashtiruvi tugallangandan va tovarlar muayyan rejimga joylashtirilgandan keyin BYDga o‘zgartirish yoki qo‘shimcha kiritish qancha muddat ichida mumkin?",
    "textRu": "",
    "optionAUz": "6 oy",
    "optionARu": "",
    "optionBUz": "1 yil",
    "optionBRu": "",
    "optionCUz": "2 yil",
    "optionCRu": "",
    "optionDUz": "3 yil",
    "optionDRu": "",
    "correctOption": "D",
    "isActive": true
  },
  {
    "sortOrder": 70,
    "difficulty": "VERY_HARD",
    "textUz": "Olib chiqilayotgan tovarlarga doir BYD qaysi paytgacha qaytarib olinishi mumkin?",
    "textRu": "",
    "optionAUz": "Faqat ro‘yxatdan o‘tguniga qadar",
    "optionARu": "",
    "optionBUz": "Tovarlarni olib chiqishga ruxsat berilgandan keyin ham, ular amalda olib chiqilguniga qadar",
    "optionBRu": "",
    "optionCUz": "Faqat bojxona ko‘rigidan oldin",
    "optionCRu": "",
    "optionDUz": "Hech qachon qaytarib olinmaydi",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 71,
    "difficulty": "VERY_HARD",
    "textUz": "Elektron BYDga o‘zgartirish va (yoki) qo‘shimcha kiritish odatda qanday amalga oshiriladi?",
    "textRu": "",
    "optionAUz": "Faqat qog‘oz ariza bilan",
    "optionARu": "",
    "optionBUz": "BDT taqdim etish orqali",
    "optionBRu": "",
    "optionCUz": "Faqat sud qarori bilan",
    "optionCRu": "",
    "optionDUz": "Faqat bojxona ko‘rsatmasi bilan",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 72,
    "difficulty": "VERY_HARD",
    "textUz": "Bojxona organlari deklaratsiyalovchi shaxsdan ilgari taqdim etilgan hujjatlarni qayta ilova qilishni qachon talab qilmaydi?",
    "textRu": "",
    "optionAUz": "Har doim talab qiladi",
    "optionARu": "",
    "optionBUz": "Faqat eksportda talab qilmaydi",
    "optionBRu": "",
    "optionCUz": "Mavjud hujjatlar takroran talab qilinmaydi, sifatsiz hujjatlar bundan mustasno",
    "optionCRu": "",
    "optionDUz": "Faqat importda talab qilinmaydi",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 73,
    "difficulty": "MEDIUM",
    "textUz": "Faqat bojxona organi to‘ldiradigan grafalarga o‘zgartirish zarur bo‘lsa, uni kim amalga oshiradi?",
    "textRu": "",
    "optionAUz": "Faqat deklarant",
    "optionARu": "",
    "optionBUz": "Faqat bojxona brokeri",
    "optionBRu": "",
    "optionCUz": "Bojxona organi xodimi, imzo va shaxsiy raqamli muhr/ERI bilan tasdiqlab",
    "optionCRu": "",
    "optionDUz": "Tashuvchi tashkilot",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 74,
    "difficulty": "VERY_HARD",
    "textUz": "Quyidagilardan qaysi biri Nizomda BYDga o‘zgartirish yoki qo‘shimcha kiritishga asos bo‘ladigan holat sifatida ko‘rsatilgan?",
    "textRu": "",
    "optionAUz": "Deklarantning telefon raqami o‘zgargani",
    "optionARu": "",
    "optionBUz": "Tovarlarni tashishga mo‘ljallangan transport vositalari texnik jihatdan nosoz bo‘lganda",
    "optionBRu": "",
    "optionCUz": "Tashqi ko‘rinish chiroyli bo‘lmaganda",
    "optionCRu": "",
    "optionDUz": "Faqat deklarant xohlaganda",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 75,
    "difficulty": "VERY_HARD",
    "textUz": "Eksport rejimiga rasmiylashtirilgan tovarlar olib chiqishga ruxsat berilgan sanadan keyin qancha muddat ichida olib chiqilmasa, BYDga tegishli harakatlar amalga oshirilishi mumkin?",
    "textRu": "",
    "optionAUz": "Avtotransportda 5 kun, boshqalarda 10 kun",
    "optionARu": "",
    "optionBUz": "Avtotransportda 10 kun, boshqa transportda 20 kun",
    "optionBRu": "",
    "optionCUz": "Hammasida 30 kun",
    "optionCRu": "",
    "optionDUz": "Faqat avtotransportda 20 kun",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 76,
    "difficulty": "VERY_HARD",
    "textUz": "Ro‘yxatga olinib, rasmiylashtirilmagan elektron BYDga o‘zgartirish yoki qo‘shimcha kiritish qaysi holatda taqiqlanadi?",
    "textRu": "",
    "optionAUz": "Tekshiruv, bojxona ko‘rigi yoki ekspertiza hali yakunlanmagan bo‘lsa",
    "optionARu": "",
    "optionBUz": "Deklarant o‘zi xato topgan bo‘lsa",
    "optionBRu": "",
    "optionCUz": "Qo‘shimcha hujjat ilova qilingan bo‘lsa",
    "optionCRu": "",
    "optionDUz": "Tovar hali omborda bo‘lsa",
    "optionDRu": "",
    "correctOption": "A",
    "isActive": true
  },
  {
    "sortOrder": 77,
    "difficulty": "VERY_HARD",
    "textUz": "Bojxona organi ro‘yxatga olinib, rasmiylashtirilmagan elektron BYD bo‘yicha murojaatni qancha muddatda ko‘rib chiqadi?",
    "textRu": "",
    "optionAUz": "Shu zahoti",
    "optionARu": "",
    "optionBUz": "Bir ish kuni ichida",
    "optionBRu": "",
    "optionCUz": "Uch ish kuni ichida",
    "optionCRu": "",
    "optionDUz": "Besh ish kuni ichida",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 78,
    "difficulty": "MEDIUM",
    "textUz": "Bojxona organi BDT yoki tegishli hujjatlarni taqdim etish muddatini qanday belgilaydi?",
    "textRu": "",
    "optionAUz": "10 kalendar kun",
    "optionARu": "",
    "optionBUz": "30 kun",
    "optionBRu": "",
    "optionCUz": "Xabardor qilingan kundan keyingi ish kuni yakuniga qadar",
    "optionCRu": "",
    "optionDUz": "Bir oy ichida",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 79,
    "difficulty": "MEDIUM",
    "textUz": "BDT yoki tegishli hujjatlar belgilangan muddatda taqdim etilmasa, odatda nima bo‘ladi?",
    "textRu": "",
    "optionAUz": "Jarima qo‘llanadi, BYD saqlanib qoladi",
    "optionARu": "",
    "optionBUz": "BYD avtomatik rasmiylashtiriladi",
    "optionBRu": "",
    "optionCUz": "Bojxona organi BYDni bekor qiladi",
    "optionCRu": "",
    "optionDUz": "Faqat ogohlantirish beriladi",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 80,
    "difficulty": "VERY_HARD",
    "textUz": "Ro‘yxatga olinib, rasmiylashtirilmagan elektron BYDni qaytarib olishga asoslar mavjud deb topilsa, u qaysi muddatda qaytariladi?",
    "textRu": "",
    "optionAUz": "Shu kunning o‘zida",
    "optionARu": "",
    "optionBUz": "Bir ish kuni davomida",
    "optionBRu": "",
    "optionCUz": "Uch ish kuni davomida",
    "optionCRu": "",
    "optionDUz": "Besh ish kuni davomida",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 81,
    "difficulty": "VERY_HARD",
    "textUz": "Rasmiylashtirilgan elektron BYDga o‘zgartirish yoki qo‘shimcha kiritish to‘g‘risida kim murojaat qilishi mumkin?",
    "textRu": "",
    "optionAUz": "Faqat deklarantning rahbari",
    "optionARu": "",
    "optionBUz": "Deklarant yoki uning nomidan ishonchnoma asosida harakat qiluvchi deklaratsiyalovchi shaxs",
    "optionBRu": "",
    "optionCUz": "Faqat bojxona posti xodimi",
    "optionCRu": "",
    "optionDUz": "Faqat sud ijrochisi",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 82,
    "difficulty": "MEDIUM",
    "textUz": "Murojaat etilayotgan yilda rasmiylashtirilgan, bojxona to‘lovlarini qaytarish bilan bog‘liq bo‘lmagan o‘zgartirishlar yuzasidan, odatda, kimga murojaat qilinadi?",
    "textRu": "",
    "optionAUz": "Hududiy bojxona boshqarmasi boshlig‘iga har doim",
    "optionARu": "",
    "optionBUz": "BYD ro‘yxatga olingan bojxona posti boshlig‘iga",
    "optionBRu": "",
    "optionCUz": "Faqat Bojxona qo‘mitasi raisiga",
    "optionCRu": "",
    "optionDUz": "Faqat prokuraturaga",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 83,
    "difficulty": "VERY_HARD",
    "textUz": "Yuqoridagi toifaga kirmaydigan boshqa hollarda BYDga o‘zgartirish yoki qo‘shimcha kiritish yuzasidan kimga murojaat qilinadi?",
    "textRu": "",
    "optionAUz": "Faqat sudga",
    "optionARu": "",
    "optionBUz": "BYD rasmiylashtirilgan hududiy bojxona boshqarmasi boshlig‘i yoki uning o‘rinbosariga",
    "optionBRu": "",
    "optionCUz": "Faqat bankka",
    "optionCRu": "",
    "optionDUz": "Faqat deklarantning o‘ziga",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 84,
    "difficulty": "VERY_HARD",
    "textUz": "Rasmiylashtirilgan BYDga o‘zgartirish yoki qo‘shimcha kiritish yuzasidan ijobiy javob xati olingandan so‘ng deklarant yoki deklaratsiyalovchi shaxs BDT va (yoki) hujjatlarni qancha muddatda taqdim etishi kerak?",
    "textRu": "",
    "optionAUz": "1 kun ichida",
    "optionARu": "",
    "optionBUz": "3 kun ichida",
    "optionBRu": "",
    "optionCUz": "5 kundan kechiktirmay",
    "optionCRu": "",
    "optionDUz": "15 kun ichida",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 85,
    "difficulty": "VERY_HARD",
    "textUz": "Bojxona organi tashabbusi bilan BYDga o‘zgartirish yoki qo‘shimcha kiritish bo‘yicha xat olingach, deklarant yoki deklaratsiyalovchi shaxs qancha muddatda javob chorasi ko‘rishi kerak?",
    "textRu": "",
    "optionAUz": "24 soat ichida",
    "optionARu": "",
    "optionBUz": "5 kundan kechiktirmay",
    "optionBRu": "",
    "optionCUz": "10 kun ichida",
    "optionCRu": "",
    "optionDUz": "1 oy ichida",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 86,
    "difficulty": "VERY_HARD",
    "textUz": "Deklarant asoslangan sabablarga ko‘ra BYDni taqdim qila olmasa, bojxona organi qachon mustaqil ravishda o‘zgartirish kiritishi mumkin?",
    "textRu": "",
    "optionAUz": "Har qanday holatda",
    "optionARu": "",
    "optionBUz": "Faqat sud qarori bilan",
    "optionBRu": "",
    "optionCUz": "Bojxona maqsadlari uchun, biroq o‘zgartirish bojxona to‘lovlari yoki tashqi savdo kontrakti ma’lumotlariga ta’sir etmasa",
    "optionCRu": "",
    "optionDUz": "Faqat eksportda",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 87,
    "difficulty": "VERY_HARD",
    "textUz": "Deklarant arizasi bilan rasmiylashtirilgan BYDni bekor qilish qaysi holatda mumkin?",
    "textRu": "",
    "optionAUz": "Har qanday xatoda",
    "optionARu": "",
    "optionBUz": "Faqat bojxona to‘lovi qaytarilganda",
    "optionBRu": "",
    "optionCUz": "Faqat bitta tovar yuzasidan bir nechta BYD qabul qilingan holatda",
    "optionCRu": "",
    "optionDUz": "Faqat sud buyrug‘i bilan",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 88,
    "difficulty": "VERY_HARD",
    "textUz": "Rasmiylashtirilgan BYDni qaytarib olish yoki bekor qilish uchun asoslar mavjud deb topilsa, u qaysi muddatda Yagona avtomatlashtirilgan axborot tizimi orqali amalga oshiriladi?",
    "textRu": "",
    "optionAUz": "1 ish kuni",
    "optionARu": "",
    "optionBUz": "2 ish kuni",
    "optionBRu": "",
    "optionCUz": "3 ish kuni",
    "optionCRu": "",
    "optionDUz": "5 ish kuni",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 89,
    "difficulty": "VERY_HARD",
    "textUz": "Qog‘oz shaklidagi BYD qaytarilayotganda uning barcha nusxalariga qanday belgi qo‘yiladi?",
    "textRu": "",
    "optionAUz": "“BEKOR QILINDI”",
    "optionARu": "",
    "optionBUz": "“QAYTARILDI”",
    "optionBRu": "",
    "optionCUz": "“TUZATILDI”",
    "optionCRu": "",
    "optionDUz": "“QABUL QILINDI”",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 90,
    "difficulty": "VERY_HARD",
    "textUz": "Deklarant bojxona posti yoki hududiy bojxona boshqarmasining BYDga o‘zgartirish, qo‘shimcha kiritish, qayta rasmiylashtirish, qaytarib olish yoki bekor qilish bo‘yicha xati yuzasidan qayerga shikoyat qilishi mumkin?",
    "textRu": "",
    "optionAUz": "Faqat ichki auditga",
    "optionARu": "",
    "optionBUz": "Yuqori turuvchi bojxona organiga yoki sudga",
    "optionBRu": "",
    "optionCUz": "Faqat soliq organiga",
    "optionCRu": "",
    "optionDUz": "Faqat bankka",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 91,
    "difficulty": "VERY_HARD",
    "textUz": "Eksport bojxona rejimida BYDning 1-grafasi birinchi bo‘linmasida qaysi belgi ko‘rsatiladi?",
    "textRu": "",
    "optionAUz": "IM",
    "optionARu": "",
    "optionBUz": "EK",
    "optionBRu": "",
    "optionCUz": "EX-40",
    "optionCRu": "",
    "optionDUz": "TR",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 92,
    "difficulty": "VERY_HARD",
    "textUz": "Eksport rejimida BYDning 1-grafasi uchinchi bo‘linmasi qanday to‘ldiriladi?",
    "textRu": "",
    "optionAUz": "Rejimning uch xonali kodi yoziladi",
    "optionARu": "",
    "optionBUz": "Davlat kodi yoziladi",
    "optionBRu": "",
    "optionCUz": "To‘ldirilmaydi",
    "optionCRu": "",
    "optionDUz": "Post kodi yoziladi",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 93,
    "difficulty": "VERY_HARD",
    "textUz": "Agar BYDda qo‘shimcha varaqlar bo‘lmasa, 3-grafada qaysi ko‘rinish to‘g‘ri hisoblanadi?",
    "textRu": "",
    "optionAUz": "0/1",
    "optionARu": "",
    "optionBUz": "1/0",
    "optionBRu": "",
    "optionCUz": "1/1",
    "optionCRu": "",
    "optionDUz": "2/1",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 94,
    "difficulty": "MEDIUM",
    "textUz": "5-grafada ko‘rsatiladigan “tovarlar nomlarining umumiy soni” nimaga mos bo‘lishi kerak?",
    "textRu": "",
    "optionAUz": "42-grafalar soniga",
    "optionARu": "",
    "optionBUz": "To‘ldirilgan 31-grafalar soniga",
    "optionBRu": "",
    "optionCUz": "45-grafalar soniga",
    "optionCRu": "",
    "optionDUz": "Qo‘shimcha varaqlar soniga",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 95,
    "difficulty": "MEDIUM",
    "textUz": "7-grafada nima ko‘rsatiladi?",
    "textRu": "",
    "optionAUz": "Eksportchi STIRi",
    "optionARu": "",
    "optionBUz": "Tovar partiyasi raqami",
    "optionBRu": "",
    "optionCUz": "BYD taqdim etiladigan bojxona postining 5 xonali kodi",
    "optionCRu": "",
    "optionDUz": "Tashqi savdo kontrakti raqami",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 96,
    "difficulty": "VERY_HARD",
    "textUz": "8-grafada eksport rejimida qanday ma’lumot qayd etiladi?",
    "textRu": "",
    "optionAUz": "Faqat bank rekvizitlari",
    "optionARu": "",
    "optionBUz": "Transport hujjatlarida ko‘rsatilgan yukni qabul qiluvchi haqidagi ma’lumotlar",
    "optionBRu": "",
    "optionCUz": "Faqat deklarantning yashash manzili",
    "optionCRu": "",
    "optionDUz": "Bojxona brokeri haqidagi ma’lumotlar",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 97,
    "difficulty": "VERY_HARD",
    "textUz": "Agar 11-grafadagi mamlakat offshor hududlar ro‘yxatiga kirsa, grafaning o‘ng bo‘linmasida qaysi kod ko‘rsatiladi?",
    "textRu": "",
    "optionAUz": "0",
    "optionARu": "",
    "optionBUz": "1",
    "optionBRu": "",
    "optionCUz": "2",
    "optionCRu": "",
    "optionDUz": "9",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 98,
    "difficulty": "MEDIUM",
    "textUz": "12-grafadagi umumiy bojxona qiymati nimaning yig‘indisidan tashkil topadi?",
    "textRu": "",
    "optionAUz": "42-grafalardagi faktura qiymatlari",
    "optionARu": "",
    "optionBUz": "46-grafalardagi statistik qiymatlar",
    "optionBRu": "",
    "optionCUz": "45-grafalardagi bojxona qiymatlari",
    "optionCRu": "",
    "optionDUz": "47-grafalardagi bojxona to‘lovlari",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 99,
    "difficulty": "MEDIUM",
    "textUz": "13-grafada qaysi kurs ko‘rsatiladi?",
    "textRu": "",
    "optionAUz": "Shartnoma tuzilgan kundagi yevro kursi",
    "optionARu": "",
    "optionBUz": "Tovar jo‘natilgan kundagi valyuta kursi",
    "optionBRu": "",
    "optionCUz": "BYD qabul qilingan kundagi AQSH dollarining milliy valyutaga nisbatan kursi",
    "optionCRu": "",
    "optionDUz": "Bojxona posti ichki kursi",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 100,
    "difficulty": "VERY_HARD",
    "textUz": "19-grafada tovar konteynerda olib o‘tilayotgan bo‘lsa, qaysi kod qo‘yiladi?",
    "textRu": "",
    "optionAUz": "0",
    "optionARu": "",
    "optionBUz": "1",
    "optionBRu": "",
    "optionCUz": "2",
    "optionCRu": "",
    "optionDUz": "9",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 101,
    "difficulty": "VERY_HARD",
    "textUz": "20-grafaning birinchi bo‘linmasida nima ko‘rsatiladi?",
    "textRu": "",
    "optionAUz": "Yetkazib berish shartining raqamli kodi",
    "optionARu": "",
    "optionBUz": "Faqat geografik punkt",
    "optionBRu": "",
    "optionCUz": "Hisob-kitob valyutasi kodi",
    "optionCRu": "",
    "optionDUz": "Bojxona to‘lovi kodi",
    "optionDRu": "",
    "correctOption": "A",
    "isActive": true
  },
  {
    "sortOrder": 102,
    "difficulty": "VERY_HARD",
    "textUz": "Eksport qilinayotgan tovarlar uchun 20-grafaning uchinchi bo‘linmasida “10” kodi nimani bildiradi?",
    "textRu": "",
    "optionAUz": "Akkreditiv",
    "optionARu": "",
    "optionBUz": "Konsignatsiya",
    "optionBRu": "",
    "optionCUz": "Oldindan to‘lov",
    "optionCRu": "",
    "optionDUz": "Barter operatsiyasi",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 103,
    "difficulty": "VERY_HARD",
    "textUz": "20-grafada tovarlarni jo‘natish shaklining “02” kodi qaysi holatni anglatadi?",
    "textRu": "",
    "optionAUz": "Tovar to‘g‘ridan-to‘g‘ri shartnoma tuzuvchi shaxs manziliga jo‘natiladi",
    "optionARu": "",
    "optionBUz": "Tovar to‘g‘ridan-to‘g‘ri shartnoma tuzuvchi shaxs manziliga jo‘natilmaydi",
    "optionBRu": "",
    "optionCUz": "Tovar bepul beriladi",
    "optionCRu": "",
    "optionDUz": "Tovar vaqtincha olib chiqiladi",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 104,
    "difficulty": "MEDIUM",
    "textUz": "22-grafaning o‘ng bo‘linmasida nima ko‘rsatiladi?",
    "textRu": "",
    "optionAUz": "Tovarlarning umumiy statistik qiymati",
    "optionARu": "",
    "optionBUz": "Tovarlarning umumiy faktura qiymati",
    "optionBRu": "",
    "optionCUz": "Tovarlarning umumiy netto vazni",
    "optionCRu": "",
    "optionDUz": "Tovarlar soni",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 105,
    "difficulty": "VERY_HARD",
    "textUz": "Agar kontrakt valyutasi O‘zbekiston Respublikasi milliy valyutasi bo‘lsa, 23-grafada qanday yozuv ko‘rsatiladi?",
    "textRu": "",
    "optionAUz": "0/0",
    "optionARu": "",
    "optionBUz": "1/0",
    "optionBRu": "",
    "optionCUz": "1/1",
    "optionCRu": "",
    "optionDUz": "100/100",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 106,
    "difficulty": "VERY_HARD",
    "textUz": "24-grafaning o‘ng bo‘linmasida nima ko‘rsatiladi?",
    "textRu": "",
    "optionAUz": "Yetkazib berish shartining harfli kodi",
    "optionARu": "",
    "optionBUz": "Kontragent bilan hisob-kitob valyutasining raqamli kodi",
    "optionBRu": "",
    "optionCUz": "Tovarning kelib chiqish mamlakati kodi",
    "optionCRu": "",
    "optionDUz": "Bojxona posti kodi",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 107,
    "difficulty": "VERY_HARD",
    "textUz": "29-grafada qanday ma’lumot ko‘rsatiladi?",
    "textRu": "",
    "optionAUz": "Tovar turgan joy manzili",
    "optionARu": "",
    "optionBUz": "Tovarni ishlab chiqargan korxona nomi",
    "optionBRu": "",
    "optionCUz": "Tovar O‘zbekistondan olib chiqiladigan bojxona postining kodi va nomi",
    "optionCRu": "",
    "optionDUz": "Deklarantning STIRi",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 108,
    "difficulty": "MEDIUM",
    "textUz": "Qaysi holatda 30-grafa to‘ldirilmaydi?",
    "textRu": "",
    "optionAUz": "Tovar temir yo‘l stansiyasida turganda",
    "optionARu": "",
    "optionBUz": "Tovar bojxona omborida turganda",
    "optionBRu": "",
    "optionCUz": "Tovar quvur transporti yoki elektr uzatish liniyalari orqali olib o‘tilganda",
    "optionCRu": "",
    "optionDUz": "Tovar erkin omborda turganda",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  },
  {
    "sortOrder": 109,
    "difficulty": "VERY_HARD",
    "textUz": "31-grafada tovar tavsifi qanday bo‘lishi kerak?",
    "textRu": "",
    "optionAUz": "Faqat tovar pozitsiyasining umumiy nomi kifoya",
    "optionARu": "",
    "optionBUz": "TIF TN bo‘yicha 10 xonali podsubpozitsiyada aniq tasniflash imkonini beradigan darajada batafsil bo‘lishi kerak",
    "optionBRu": "",
    "optionCUz": "Faqat marka yozilishi kifoya",
    "optionCRu": "",
    "optionDUz": "Faqat ishlab chiqaruvchi mamlakat ko‘rsatiladi",
    "optionDRu": "",
    "correctOption": "B",
    "isActive": true
  },
  {
    "sortOrder": 110,
    "difficulty": "VERY_HARD",
    "textUz": "46-grafadagi statistik qiymat qanday aniqlikda ko‘rsatiladi?",
    "textRu": "",
    "optionAUz": "Verguldan so‘ng 1 belgigacha",
    "optionARu": "",
    "optionBUz": "Verguldan so‘ng 2 belgigacha",
    "optionBRu": "",
    "optionCUz": "Verguldan so‘ng 3 belgigacha",
    "optionCRu": "",
    "optionDUz": "Butun son ko‘rinishida",
    "optionDRu": "",
    "correctOption": "C",
    "isActive": true
  }
] as const;
